### ISSUE TITLE
is-inside.me

### ISSUE THREAD

**Issue by Kadantte** [eggsy/is-inside-me-dead#2]
Thanks, guys for the ride <3 I want to ask you guys if you think about making the code source for is-inside.me available for the public?

**Comment by Tresmos** [comment]
For everyone's eye and mental health, unfortunately no. It is just too messy and there is nothing interesting tbh 😁. These made it all possible tho: 

https://www.npmjs.com/package/wildcard-subdomains
https://www.npmjs.com/package/express-fileupload

**Comment by eggsy** [comment]
Thank you for getting in touch with us here and I hope that answers your questions. I'm closing this issue now.

**Comment by Kadantte** [comment]
thanks, guys for the answer!
